.text
.align 2

.global ___gnu_thumb1_case_sqi
___gnu_thumb1_case_sqi:
	tj ____gnu_thumb1_case_sqi

.global ___gnu_thumb1_case_uqi
___gnu_thumb1_case_uqi:
	tj ____gnu_thumb1_case_uqi

.global ___gnu_thumb1_case_shi
___gnu_thumb1_case_shi:
	tj ____gnu_thumb1_case_shi

.global ___gnu_thumb1_case_uhi
___gnu_thumb1_case_uhi:
	tj ____gnu_thumb1_case_uhi

.global ___gnu_thumb1_case_si
___gnu_thumb1_case_si:
	tj ____gnu_thumb1_case_si
